repos:
-   repo: local
    hooks:
    -   id: update-readme
        name: Update README with script list
        entry: python -m dsbin.update_readme
        language: system
        pass_filenames: false
        always_run: true
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.2
    hooks:
    -   id: ruff
        args: [--config, ruff.toml, --preview, --fix, --unsafe-fixes]
    -   id: ruff-format
