[tool.poetry]
name = "dsbin"
version = "1.2.3"
description = "Personal Python scripts"
authors = ["Danny Stewart <danny@stewart.cc>"]
readme = "README.md"
packages = [{include = "dsbin", from = "src"}]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = "^3.12"
iplookup = {git = "https://gitlab.dannystewart.com/danny/ip-lookup.git"}
dsupdater = { git = "https://gitlab.dannystewart.com/danny/dsupdater.git" }
dsutil = { git = "https://gitlab.dannystewart.com/danny/dsutil.git" }
"path.py" = ">=12.5.0"
azure-storage-blob = ">=12.24.0"
halo = ">=0.0.31"
inquirer = ">=3.4.0"
mutagen = ">=1.47.0"
mysql-connector-python = ">=9.1.0"
natsort = ">=8.4.0"
numpy = ">=2.0.2"
paramiko = ">=3.5.0"
pathlib = ">=1.0.1"
pillow = ">=11.0.0"
pydub = ">=0.25.1"
pygments = ">=2.18.0"
pyperclip = ">=1.9.0"
python-dotenv = ">=1.0.1"
requests = ">=2.32.3"
ruamel-yaml = ">=0.18.6"
scipy = ">=1.14.1"
scp = ">=0.15.0"
soundfile = ">=0.12.1"
termcolor = ">=2.5.0"
tomli-w = "^1.1.0"
types-paramiko = ">=3.5.0.20240928"
types-pillow = ">=10.2.0.20240822"
types-requests = ">=2.32.0.20241016"
types-send2trash = ">=1.8.2.7"

[tool.poetry.group.dev.dependencies]
mypy = ">=1.13.0"
ruff = ">=0.8.2"

[tool.poetry.scripts]
# Script to list all scripts
lsbin = "dsbin.lsbin:main"

# File management scripts
backupsort = "dsbin.files.backupsort:main"
bigfiles = "dsbin.files.bigfiles:main"
dupefinder = "dsbin.files.dupefinder:main"
fml = "dsbin.files.fml:main"
foldermerge = "dsbin.files.foldermerge:main"
rsyncer = "dsbin.files.rsyncer:main"

# Media scripts
ffgif = "dsbin.media.ffgif:main"
fftrim = "dsbin.media.fftrim:main"
ytdl = "dsbin.media.ytdl:main"

# Music scripts
aif2wav = "dsbin.music.awa:aif2wav"
alacrity = "dsbin.music.alacrity:main"
azmusic = "dsbin.music.azmusic:main"
bounceprune = "dsbin.music.bounceprune:main"
calcbounce = "dsbin.music.calcbounce:main"
evtelegram = "dsbin.music.evtelegram:main"
hpfilter = "dsbin.music.hpfilter:main"
metacopy = "dsbin.music.metacopy:main"
mp3ify = "dsbin.music.mp3ify:main"
mshare = "dsbin.music.mshare:main"
pybounce = "dsbin.music.pybounce:main"
pyfiler = "dsbin.music.pyfiler:main"
rmp3 = "dsbin.music.rmp3:main"
wav2aif = "dsbin.music.awa:wav2aif"
wpmusic = "dsbin.music.wpmusic.main:main"

# Logic-specific scripts
bipclean = "dsbin.logic.bipclean:main"
oldprojects = "dsbin.logic.oldprojects:main"

# Mac-specific scripts
dmgify = "dsbin.mac.dmgify:main"
mvdmg = "dsbin.mac.mvdmg:main"
netreset = "dsbin.mac.netreset:main"
pkginst = "dsbin.mac.pkginst:main"
setmag = "dsbin.mac.setmag:main"
spacepurger = "dsbin.mac.spacepurger:main"
timestamps = "dsbin.mac.timestamps:main"

# Development-related scripts
dsbots = "dsbin.dev.dsbots.dsbots:main"
dsbump = "dsbin.dev.pyversioner:script_bump"
dspause = "dsbin.dev.pyversioner:script_pause"
dstag = "dsbin.dev.pyversioner:script_tag"
dsversion = "dsbin.dev.pyversioner:main"
gitcalc = "dsbin.dev.gitcalc.main:main"
pipmigrator = "dsbin.dev.pipmigrator:main"
pyenversioner = "dsbin.dev.pyenversioner:main"
scriptdep = "dsbin.dev.scriptdep:main"
uvmigrate = "dsbin.dev.uvmigrate:main"

# System tools
changehostname = "dsbin.tools.changehostname:main"
dsservice = "dsbin.tools.dsservice:main"
distro = "dsbin.tools.distro:main"
dockermounter = "dsbin.tools.dockermounter:main"
envsync = "dsbin.tools.envsync:main"
iplookup = "iplookup.iplookup:main"
ssh-tunnel = "dsbin.tools.ssh_tunnel:main"
watchtower = "dsbin.tools.watchtower:main"

# Text processing scripts
pycompare = "dsbin.text.pycompare:main"
w11renamer = "dsbin.text.w11renamer:main"
