[tool.poetry]
name = "dsbin"
version = "0.3.0"
description = "Personal Python scripts"
authors = ["Danny Stewart <danny@stewart.cc>"]
readme = "README.md"
packages = [{include = "dsbin", from = "src"}]

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
dsmusic = { git = "https://gitlab.dannystewart.com/danny/dsmusic.git" }
dsupdater = { git = "https://gitlab.dannystewart.com/danny/updater.git" }
dsutil = { git = "https://gitlab.dannystewart.com/danny/dsutil.git" }
"path.py" = "^12.5.0"
argparse = "^1.4.0"
azure-storage-blob = "^12.23.1"
halo = "^0.0.31"
inquirer = "^3.4.0"
mutagen = "^1.47.0"
natsort = "^8.4.0"
numpy = ">=2.0.2"
paramiko = "^3.5.0"
pathlib = "^1.0.1"
pillow = "^11.0.0"
pydub = "^0.25.1"
pygments = "^2.18.0"
pyperclip = "^1.9.0"
python-dotenv = "^1.0.1"
requests = "^2.32.3"
scipy = "^1.14.1"
scp = "^0.15.0"
soundfile = "^0.12.1"
termcolor = "^2.5.0"

[tool.poetry.group.dev.dependencies]
mypy = "^1.13.0"
ruff = "^0.7.2"
types-paramiko = "^3.5.0.20240928"
types-pillow = "^10.2.0.20240822"
types-requests = "^2.32.0.20241016"
types-send2trash = "^1.8.2.7"

[tool.poetry.scripts]
backupsort = "dsbin.backupsort:main"
bigfiles = "dsbin.bigfiles:main"
changehostname = "dsbin.changehostname:main"
distro = "dsbin.distro:main"
dmgify = "dsbin.dmgify:main"
dockermounter = "dsbin.dockermounter:main"
dupefinder = "dsbin.dupefinder:main"
envscripts = "dsbin.envscripts:main"
envsync = "dsbin.envsync:main"
evtelegram = "dsbin.evtelegram:main"
ffgif = "dsbin.ffgif:main"
fftrim = "dsbin.fftrim:main"
fml = "dsbin.fml:main"
foldermerge = "dsbin.foldermerge:main"
iplookup = "dsbin.iplookup:main"
lsbin = "dsbin.lsbin:main"
metacopy = "dsbin.metacopy:main"
mp3ify = "dsbin.mp3ify:main"
mshare = "dsbin.mshare:main"
mvdmg = "dsbin.mvdmg:main"
netreset = "dsbin.netreset:main"
oldprojects = "dsbin.oldprojects:main"
pipmigrator = "dsbin.pipmigrator:main"
pkginst = "dsbin.pkginst:main"
pybounce = "dsbin.pybounce:main"
pycompare = "dsbin.pycompare:main"
pyenversioner = "dsbin.pyenversioner:main"
rmp3 = "dsbin.rmp3:main"
rsyncer = "dsbin.rsyncer:main"
scriptdep = "dsbin.scriptdep:main"
setmag = "dsbin.setmag:main"
spacepurger = "dsbin.spacepurger:main"
ssh-tunnel = "dsbin.ssh_tunnel:main"
timestamps = "dsbin.timestamps:main"
uvmigrate = "dsbin.uvmigrate:main"
w11renamer = "dsbin.w11renamer:main"
watchtower = "dsbin.watchtower:main"
ytdl = "dsbin.ytdl:main"

# Music scripts
dsmusic = "dsbin.dsmusic.main:main"
dsm = "dsbin.dsmusic.main:main"

# Direct commands
aif2wav = "dsbin.dsmusic.awa:aif2wav_main"
wav2aif = "dsbin.dsmusic.awa:wav2aif_main"
alacrity = "dsbin.dsmusic.alacrity:main"
bounceprune = "dsbin.dsmusic.bounceprune:main"
azmusic = "dsbin.dsmusic.azmusic:main"
bipclean = "dsbin.dsmusic.bipclean:main"
calc = "dsbin.dsmusic.calc:main"
filer = "dsbin.dsmusic.filer:main"
hpfilter = "dsbin.dsmusic.hpfilter:main"
wpmusic = "dsbin.dsmusic.wpmusic:main"

# Aliases
bp = "dsbin.dsmusic.bounceprune:main"
prune = "dsbin.dsmusic.bounceprune:main"
alac = "dsbin.dsmusic.alacrity:main"
wp = "dsbin.dsmusic.wpmusic:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
ignore_missing_imports = true
