# Auto-generated completions for timestamps
complete -c timestamps -d "File to get or set timestamps for"
complete -c timestamps -s c -l creation -d "Creation timestamp to set"
complete -c timestamps -s m -l modification -d "Modification timestamp to set"
complete -c timestamps -l copy -d "Copy timestamps from one file to another"
complete -c timestamps -l copy-from -d "Source file to copy timestamps from"
complete -c timestamps -l copy-to -d "Destination file to copy timestamps to"
complete -c timestamps -l src-dir -d "Source directory for copying timestamps from"
complete -c timestamps -l dest-dir -d "Destination directory for copying timestamps to"
complete -c timestamps -l ctime-to-mtime -d "Copy creation time to modification time"
complete -c timestamps -l mtime-to-ctime -d "Copy modification time to creation time"
