# Auto-generated completions for wpmusic
complete -c wpmusic -l skip-upload -d "convert only, skip uploading (implies --keep-files)"
complete -c wpmusic -l keep-files -d "keep converted files after upload"
complete -c wpmusic -l append -d "append text to the song title"
complete -c wpmusic -l doc -d "show the full documentation and exit"
complete -c wpmusic -l history -d "display upload history, optionally filtered by track name"
complete -c wpmusic -s l -l list -d "number of uploads to list per track (default: 3)"
complete -c wpmusic -l force-refresh -d "force refresh of local cache from MySQL server"
complete -c wpmusic -l no-cache -d "bypass local cache, always use MySQL server directly"
complete -c wpmusic -l check-db -d "test database connection and exit"
